# lower this if you are on a memory-constrained system
org.gradle.jvmargs=-Xmx4G
# turn this off if you dont like how your CPU gets slammed while decompiling
org.gradle.parallel=true

# the version of minecraft
minecraft_version=1.21.11
# https://parchmentmc.org/docs/getting-started provide parameter names and javadocs
parchment_mappings=1.21.11:2025.12.20
# https://fabricmc.net/develop/ alternative to official mappings (not enabled by default)
yarn_mappings=1.21.11+build.6
